# Generated by Django 3.2.1 on 2021-05-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='user',
            new_name='user_set',
        ),
    ]
