# Generated by Django 3.2.1 on 2021-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='grade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
